// Autogenerated from Pigeon (v0.1.9), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class TextureMessage;
@class CreateMessage;
@class LoopingMessage;
@class VolumeMessage;
@class PlaybackSpeedMessage;
@class PositionMessage;

@interface TextureMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * textureId;
@end

@interface CreateMessage : NSObject
@property(nonatomic, copy, nullable) NSString * asset;
@property(nonatomic, copy, nullable) NSString * uri;
@property(nonatomic, copy, nullable) NSString * packageName;
@property(nonatomic, copy, nullable) NSString * formatHint;
@end

@interface LoopingMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * textureId;
@property(nonatomic, strong, nullable) NSNumber * isLooping;
@end

@interface VolumeMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * textureId;
@property(nonatomic, strong, nullable) NSNumber * volume;
@end

@interface PlaybackSpeedMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * textureId;
@property(nonatomic, strong, nullable) NSNumber * speed;
@end

@interface PositionMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * textureId;
@property(nonatomic, strong, nullable) NSNumber * position;
@end

@protocol VlcPlayerApi
-(void)initialize:(FlutterError *_Nullable *_Nonnull)error;
-(nullable TextureMessage *)create:(CreateMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)dispose:(TextureMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setLooping:(LoopingMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setVolume:(VolumeMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setPlaybackSpeed:(PlaybackSpeedMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)play:(TextureMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(nullable PositionMessage *)position:(TextureMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)seekTo:(PositionMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)pause:(TextureMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void VlcPlayerApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<VlcPlayerApi> _Nullable api);

NS_ASSUME_NONNULL_END
