name: flutter_vlc_player
description: A VLC-powered alternative to Flutter's video_player. Supports multiple players on one screen.
version: 4.0.1
homepage: https://github.com/solid-software/flutter_vlc_player

environment:
  sdk: ">=2.1.0 <3.0.0"
  # Flutter versions prior to 1.10 did not support
  # the flutter.plugin.platforms.
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cryptoutils: ^0.4.0
  flutter_vlc_player_platform_interface:
    path: ../flutter_vlc_player_platform_interface/

flutter:
  plugin:
    platforms:
      android:
        package: software.solid.fluttervlcplayer
        pluginClass: FlutterVlcPlayerPlugin
      ios:
        pluginClass: FlutterVlcPlayerPlugin